# Created by hand for rpi; see packaging/README.md in bigfish1913/pi-rust
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bigfish1913.rpi
PackageVersion: 0.3.12
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: rpi.exe
    PortableCommandAlias: rpi
  InstallerUrl: https://github.com/bigfish1913/pi-rust/releases/download/v0.3.12/rpi-v0.3.12-x86_64-pc-windows-msvc.zip
  InstallerSha256: 7399754258762F599E22327EAF8687DE44F38755D496436D7FF1FDDD4D043BA8
ManifestType: installer
ManifestVersion: 1.12.0
