# Created by hand for rpi; see packaging/README.md in bigfish1913/pi-rust
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bigfish1913.rpi
PackageVersion: 0.3.10
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: rpi.exe
    PortableCommandAlias: rpi
  InstallerUrl: https://github.com/bigfish1913/pi-rust/releases/download/v0.3.10/rpi-v0.3.10-x86_64-pc-windows-msvc.zip
  InstallerSha256: 3DC9B6489D26C4C3903D7CADF4AE8820DA795964A945163970EEF07FB1F4FB92
ManifestType: installer
ManifestVersion: 1.12.0
