# Created by hand for rpi; see packaging/README.md in bigfish1913/pi-rust
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bigfish1913.rpi
PackageVersion: 0.3.18
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-10
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: rpi.exe
    PortableCommandAlias: rpi
  InstallerUrl: https://github.com/bigfish1913/pi-rust/releases/download/v0.3.18/rpi-v0.3.18-x86_64-pc-windows-msvc.zip
  InstallerSha256: 0C00A7271FDC50E1AAB1E5AC7B7EE2BA2942BCE3BC2916D5A66E61699BC5CA5A
ManifestType: installer
ManifestVersion: 1.12.0
