# Created by hand for rpi; see packaging/README.md in bigfish1913/pi-rust
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bigfish1913.rpi
PackageVersion: 0.3.6
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-09-30
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: rpi.exe
    PortableCommandAlias: rpi
  InstallerUrl: https://github.com/bigfish1913/pi-rust/releases/download/v0.3.6/rpi-v0.3.6-x86_64-pc-windows-msvc.zip
  InstallerSha256: 1F62154581FD5CB3C6E60EAD2A7D28A124695280627540477C0B55E7E6F0BD82
ManifestType: installer
ManifestVersion: 1.12.0
