# Created by hand for rpi; see packaging/README.md in bigfish1913/pi-rust
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bigfish1913.rpi
PackageVersion: 0.3.16
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-06
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: rpi.exe
    PortableCommandAlias: rpi
  InstallerUrl: https://github.com/bigfish1913/pi-rust/releases/download/v0.3.16/rpi-v0.3.16-x86_64-pc-windows-msvc.zip
  InstallerSha256: D0DEBE018560DEF9176B75C9B9299312DB0EED4342F0DC389B6A0785B53E31C8
ManifestType: installer
ManifestVersion: 1.12.0
