# Created by hand for rpi; see packaging/README.md in bigfish1913/pi-rust
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: bigfish1913.rpi
PackageVersion: 0.3.17
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: rpi.exe
    PortableCommandAlias: rpi
  InstallerUrl: https://github.com/bigfish1913/pi-rust/releases/download/v0.3.17/rpi-v0.3.17-x86_64-pc-windows-msvc.zip
  InstallerSha256: 0EC8186F31EE8EAE624685668B4B65D08B7B41A25A2FC11BDC77E1BBC9E10863
ManifestType: installer
ManifestVersion: 1.12.0
